services:
  - type: web
    name: twod3d-lottery
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./public
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: API_URL
        value: https://twod3d-lottery-api-q68w.onrender.com
      - key: APP_ENV
        value: production
