services:
  - type: web
    name: 2d3d-lottery-frontend
    env: static
    buildCommand: |
      npm install
      npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://2d3d-lottery-backend.onrender.com
      - key: NODE_VERSION
        value: 18.17.0 