services:
  - type: web
    name: twod3d-lottery-api
    env: php
    plan: starter
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: heroku-php-apache2 public/
    healthCheckPath: /health.php
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_HOST
        fromDatabase:
          name: twod3d-lottery-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: twod3d-lottery-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: twod3d-lottery-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: twod3d-lottery-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://twod3d-lottery.onrender.com
      - key: REDIS_HOST
        fromService:
          type: redis
          name: twod3d-lottery-cache
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: twod3d-lottery-cache
          property: port
      - key: REDIS_PASSWORD
        fromService:
          type: redis
          name: twod3d-lottery-cache
          property: password

  - type: redis
    name: twod3d-lottery-cache
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

databases:
  - name: twod3d-lottery-db
    plan: free
    ipAllowList: [] 